Basic DevOps Testing

diff --git a/.github/workflows/promote_xmCloud.yml b/.github/workflows/promote_xmCloud.yml
--- a/.github/workflows/promote_xmCloud.yml
+++ b/.github/workflows/promote_xmCloud.yml
@@ -24,27 +24,27 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
-    - uses: actions/setup-dotnet@v2
-      with:
-        dotnet-version: '6.0.x' 
-    - run: dotnet tool restore
-    - run: dotnet sitecore --help
-    - name: Authenticate CLI with XM Cloud
-      run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }} --allow-write
-    - name: Deploy the CM assets to XM Cloud
-      run: |
-        result=$(dotnet sitecore cloud environment promote --environment-id ${{ secrets.XM_CLOUD_ENVIRONMENT_ID }} --source-id ${{ inputs.deploymentId }} --json)
-        echo $result
-        isTimedOut=$(echo $result | jq ' .IsTimedOut')
-        isCompleted=$(echo $result | jq ' .IsCompleted')
-        if [ $isTimedOut = true ]
-        then
-            echo "Operation Timed Out."
-            exit -1
-        fi  
-        if ! [ $isCompleted = true ]
-        then
-            echo "Operation Failed."
-            exit -1
-        fi
-        echo "Deployment Completed"
+    # - uses: actions/setup-dotnet@v2
+    #   with:
+    #     dotnet-version: '6.0.x' 
+    # - run: dotnet tool restore
+    # - run: dotnet sitecore --help
+    # - name: Authenticate CLI with XM Cloud
+    #   run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.XM_CLOUD_CLIENT_ID }} --client-secret ${{ secrets.XM_CLOUD_CLIENT_SECRET }} --allow-write
+    # - name: Deploy the CM assets to XM Cloud
+    #   run: |
+    #     result=$(dotnet sitecore cloud environment promote --environment-id ${{ secrets.XM_CLOUD_ENVIRONMENT_ID }} --source-id ${{ inputs.deploymentId }} --json)
+    #     echo $result
+    #     isTimedOut=$(echo $result | jq ' .IsTimedOut')
+    #     isCompleted=$(echo $result | jq ' .IsCompleted')
+    #     if [ $isTimedOut = true ]
+    #     then
+    #         echo "Operation Timed Out."
+    #         exit -1
+    #     fi  
+    #     if ! [ $isCompleted = true ]
+    #     then
+    #         echo "Operation Failed."
+    #         exit -1
+    #     fi
+    #     echo "Deployment Completed"
